# Generated by Django 3.2.15 on 2024-02-26 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=1000)),
                ('id_de', models.CharField(default='', max_length=1000)),
                ('id_employe', models.CharField(default='', max_length=1000)),
                ('commentaire_reponse', models.CharField(max_length=1000)),
                ('date_init', models.DateField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['date_init'],
            },
        ),
    ]
