# Generated by Django 3.2.15 on 2024-02-26 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reponse', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Response',
            new_name='Reponse',
        ),
    ]
