# Generated by Django 3.2.15 on 2024-02-27 09:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('reponse', '0003_auto_20240226_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reponse',
            name='uuid',
            field=models.CharField(default=uuid.uuid4, max_length=1000),
        ),
    ]
