# Generated by Django 3.2.15 on 2024-02-27 14:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PropositionSanction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(default=uuid.UUID('35b151c0-485e-4c26-b42c-a48a920a652b'), max_length=100)),
                ('date_creation_prop', models.DateField(auto_now_add=True)),
                ('type_prop', models.CharField(choices=[('1', 'proposition'), ('2', 'validation')], max_length=100)),
                ('id_employe', models.CharField(max_length=100)),
                ('id_de', models.CharField(max_length=100)),
                ('sanction', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['date_creation_prop'],
            },
        ),
    ]
