# Generated by Django 3.2.15 on 2024-03-12 08:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('proposition', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propositionsanction',
            name='uuid',
            field=models.CharField(default=uuid.UUID('085672c3-383f-46d3-8d1c-4bfc1719f331'), max_length=100),
        ),
    ]
