# Generated by Django 3.2.15 on 2024-03-15 10:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('proposition', '0007_alter_propositionsanction_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propositionsanction',
            name='uuid',
            field=models.CharField(default=uuid.UUID('c030a87f-7aab-4471-a4c6-0de70fea93ae'), max_length=100),
        ),
    ]
