# Generated by Django 3.2.15 on 2024-03-15 10:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('proposition', '0008_alter_propositionsanction_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propositionsanction',
            name='uuid',
            field=models.CharField(default=uuid.UUID('e493fe56-2eaf-4441-8c08-1990c977cf53'), max_length=100),
        ),
    ]
