# Generated by Django 3.2.15 on 2024-03-22 03:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('proposition', '0009_alter_propositionsanction_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propositionsanction',
            name='uuid',
            field=models.CharField(default=uuid.UUID('00045e82-c137-4bd2-ba37-39572ea8d0d2'), max_length=100),
        ),
    ]
