# Generated by Django 3.2.15 on 2024-03-22 03:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('proposition', '0010_alter_propositionsanction_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propositionsanction',
            name='uuid',
            field=models.CharField(default=uuid.UUID('1d17aaff-6e06-45f0-a0cb-e01373dccfcd'), max_length=100),
        ),
    ]
