# Generated by Django 3.2.15 on 2024-03-27 16:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('proposition', '0011_alter_propositionsanction_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propositionsanction',
            name='uuid',
            field=models.CharField(default=uuid.UUID('bd55b325-302c-4a1c-8e42-8ddc7933dfee'), max_length=100),
        ),
    ]
