# Generated by Django 3.2.15 on 2024-03-28 11:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('proposition', '0012_alter_propositionsanction_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propositionsanction',
            name='uuid',
            field=models.CharField(default=uuid.UUID('4874d202-025b-4976-9381-d15622269d2e'), max_length=100),
        ),
    ]
