# Generated by Django 3.2.15 on 2024-03-28 11:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('proposition', '0013_alter_propositionsanction_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propositionsanction',
            name='uuid',
            field=models.CharField(default=uuid.UUID('4813a69a-d1e3-4b32-939f-cdca5c2a747a'), max_length=100),
        ),
    ]
