# Generated by Django 3.2.15 on 2024-03-28 11:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('proposition', '0014_alter_propositionsanction_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propositionsanction',
            name='uuid',
            field=models.CharField(default=uuid.UUID('4693b58a-179d-4e5b-b9be-a7c9ca9029e2'), max_length=100),
        ),
    ]
