# Generated by Django 3.2.15 on 2024-03-28 11:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('proposition', '0015_alter_propositionsanction_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propositionsanction',
            name='uuid',
            field=models.CharField(default=uuid.UUID('64e30848-8fac-49ac-97d2-8d4655d9c514'), max_length=100),
        ),
    ]
