# Generated by Django 3.2.15 on 2024-03-28 12:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('proposition', '0016_alter_propositionsanction_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propositionsanction',
            name='uuid',
            field=models.CharField(default=uuid.UUID('a49434be-7c56-44fe-8d03-1581abc99a8f'), max_length=100),
        ),
    ]
