# Generated by Django 3.2.15 on 2024-04-04 11:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('proposition', '0017_alter_propositionsanction_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propositionsanction',
            name='uuid',
            field=models.CharField(default=uuid.UUID('c7059c72-90ce-4eac-a607-f9293ab81112'), max_length=100),
        ),
    ]
