# Generated by Django 3.2.15 on 2024-04-04 11:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('proposition', '0018_alter_propositionsanction_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propositionsanction',
            name='uuid',
            field=models.CharField(default=uuid.UUID('81b2aef5-d427-4485-afe3-8c535e1fa186'), max_length=100),
        ),
    ]
