# Generated by Django 3.2.15 on 2024-04-04 11:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('proposition', '0020_alter_propositionsanction_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propositionsanction',
            name='uuid',
            field=models.CharField(default=uuid.UUID('25e4721e-9453-46fc-9f2a-94fc0eddfc49'), max_length=100),
        ),
    ]
