# Generated by Django 3.2.15 on 2024-04-04 11:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('proposition', '0021_alter_propositionsanction_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propositionsanction',
            name='uuid',
            field=models.CharField(default=uuid.UUID('ddb53efe-fed3-41a5-8390-19fbdf475b69'), max_length=100),
        ),
    ]
