# Generated by Django 3.2.15 on 2024-04-04 15:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('proposition', '0022_alter_propositionsanction_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propositionsanction',
            name='uuid',
            field=models.CharField(default=uuid.UUID('ea5db9a6-c8a4-43b0-8375-3c04a48a369f'), max_length=100),
        ),
    ]
