# Generated by Django 3.2.15 on 2024-04-09 15:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('proposition', '0023_alter_propositionsanction_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propositionsanction',
            name='uuid',
            field=models.CharField(default=uuid.UUID('e4728d34-f3b9-46f3-9694-9cc9ff790f08'), max_length=100),
        ),
    ]
