# Generated by Django 3.2 on 2023-06-23 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Motif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=100)),
                ('entity', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=100)),
                ('rubrique', models.CharField(choices=[('1', 'de'), ('2', 'da'), ('3', 'conge')], default='1', max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('date_init', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['nom', 'date_init'],
            },
        ),
    ]
