# Generated by Django 3.2.15 on 2023-09-08 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motif',
            name='rubrique',
            field=models.CharField(choices=[('demande_explication', 'DE'), ('demande_permission_absence', 'DPA'), ('conge', 'conge')], max_length=70),
        ),
    ]
