# Generated by Django 3.2.15 on 2024-03-28 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20240327_1503'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MotifSanction',
        ),
    ]
