# Generated by Django 3.2.15 on 2024-04-04 11:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MotifSanction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(default=uuid.uuid4, max_length=100)),
                ('motif_id', models.CharField(max_length=100)),
                ('sanction_id', models.CharField(max_length=100)),
                ('date_init', models.DateField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sanction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(default=uuid.UUID('23c05959-0211-49da-b605-ddc35d302446'), max_length=100)),
                ('libelle_sanction', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('id_entity', models.CharField(max_length=1000)),
                ('power', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['libelle_sanction', 'description', 'uuid'],
            },
        ),
    ]
