# Generated by Django 3.2.15 on 2024-02-27 10:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sanction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(default=uuid.UUID('4050cfbf-8555-4531-816f-eafe950ba448'), max_length=100)),
                ('libelle_sanction', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('id_entity', models.CharField(max_length=1000)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['libelle_sanction', 'description', 'uuid'],
            },
        ),
    ]
