# Generated by Django 3.2.15 on 2024-04-04 11:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sanction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sanction',
            name='uuid',
            field=models.CharField(default=uuid.UUID('df7123b2-0444-4bee-9b95-74187523bf67'), max_length=100),
        ),
    ]
