# Generated by Django 3.2.15 on 2024-04-04 11:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sanction', '0002_alter_sanction_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sanction',
            name='uuid',
            field=models.CharField(default=uuid.UUID('82c3452a-62b6-457e-96a2-2d9c7a756128'), max_length=100),
        ),
    ]
