# Generated by Django 3.2.15 on 2024-04-04 11:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sanction', '0003_alter_sanction_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sanction',
            name='uuid',
            field=models.CharField(default=uuid.UUID('b410eab8-aad6-4133-8cad-31ff4b50c2d9'), max_length=100),
        ),
    ]
