# Generated by Django 3.2.15 on 2024-03-12 08:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sanction', '0003_alter_sanction_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sanction',
            name='uuid',
            field=models.CharField(default=uuid.UUID('f23ee550-2b8e-4fa3-ae71-389633a7a8f4'), max_length=100),
        ),
    ]
