# Generated by Django 3.2.15 on 2024-04-04 11:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sanction', '0004_alter_sanction_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sanction',
            name='uuid',
            field=models.CharField(default=uuid.UUID('6f41edc8-4286-4c3b-bb3c-c240600db16a'), max_length=100),
        ),
    ]
