# Generated by Django 3.2.15 on 2024-04-04 15:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sanction', '0005_alter_sanction_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sanction',
            name='uuid',
            field=models.CharField(default=uuid.UUID('f24cf69f-807f-4fdb-bde0-c6f5f6df5d5f'), max_length=100),
        ),
    ]
