# Generated by Django 3.2.15 on 2024-04-04 15:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sanction', '0006_alter_sanction_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sanction',
            name='uuid',
            field=models.CharField(default=uuid.UUID('53b36eee-7ccb-4a34-b7db-f1d1ba873c34'), max_length=100),
        ),
    ]
