# Generated by Django 3.2.15 on 2024-03-12 08:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sanction', '0006_alter_sanction_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sanction',
            name='uuid',
            field=models.CharField(default=uuid.UUID('77f97498-b8c4-45c5-aca6-d7b67cc6ee3e'), max_length=100),
        ),
    ]
