# Generated by Django 3.2.15 on 2024-03-15 10:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sanction', '0009_alter_sanction_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sanction',
            name='uuid',
            field=models.CharField(default=uuid.UUID('70ae958f-9a19-4c90-8155-b565fa9e225e'), max_length=100),
        ),
    ]
