# Generated by Django 3.2.15 on 2024-03-22 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('temoins', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Temoins',
            new_name='Temoin',
        ),
    ]
