# Generated by Django 3.2.15 on 2024-02-19 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeExplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=100)),
                ('code_de', models.CharField(max_length=100)),
                ('employer_initiateur', models.CharField(max_length=100)),
                ('employer_recepteur', models.CharField(max_length=100)),
                ('description', models.CharField(default='', max_length=2550)),
                ('motif', models.CharField(max_length=100)),
                ('date_init', models.DateField(auto_now_add=True)),
                ('date_response', models.DateField(null=True)),
                ('date_validation', models.DateField(blank=True, null=True)),
                ('date_archivage', models.DateField(null=True)),
                ('statut_de', models.CharField(choices=[('1', 'waiting_for_response'), ('2', 'waiting_for_sanction'), ('3', 'waiting_witness_response'), ('4', 'note_rh'), ('5', 'archiving')], default='1', max_length=20)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['statut_de', 'date_init'],
            },
        ),
    ]
