# Generated by Django 3.2.15 on 2024-02-26 09:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('demande', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandeexplication',
            name='description',
            field=models.CharField(max_length=2550),
        ),
        migrations.AlterField(
            model_name='demandeexplication',
            name='uuid',
            field=models.CharField(default=uuid.uuid4, max_length=100),
        ),
    ]
