# Generated by Django 3.2.15 on 2024-03-22 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demande', '0003_auto_20240312_0941'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='demandeexplication',
            options={'ordering': ['-date_init', '-code_de']},
        ),
        migrations.AlterField(
            model_name='demandeexplication',
            name='statut_de',
            field=models.CharField(choices=[('1', 'waiting_for_response'), ('2', 'waiting_for_sanction'), ('3', 'waiting_witness_response'), ('4', 'archieved'), ('5', 'responded_out_of_time'), ('6', 'responded_on_time')], default='1', max_length=20),
        ),
    ]
