# Generated by Django 3.2.15 on 2024-03-22 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demande', '0004_auto_20240322_0453'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandeexplication',
            name='user_id',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
